=== YusefFaruq/Web-Services-Dev/Assignment2/web/enquiries.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.rentapplication.uts.edu.au"
    xmlns="http://www.rentapplication.uts.edu.au"
    elementFormDefault="qualified">

    <xs:simpleType name="bookingdate">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}\s{1}-\s{1}\d{1,2}/\d{1,2}/\d{1,4}"/>   
        </xs:restriction>
    </xs:simpleType>    

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z0-9]+\.*_*)+@.+\.[a-z]+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="enquiries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="enquiry" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="listingid" type="xs:string"/>
                            <xs:element name="bookingdate" type="bookingdate"/>
                            <xs:element name="message" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== YusefFaruq/Web-Services-Dev/Assignment2/web/enquiries.xml
<!-- Jack Huggart -->

<enquiries xmlns="http://www.rentapplication.uts.edu.au"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.rentapplication.uts.edu.au enquiries.xsd">
    <enquiry>
        <name>Jack Lastname</name>
        <email>jacklastname@gmail.com</email>
        <listingid>1</listingid>
        <bookingdate>10/10/2016 - 15/10/2016</bookingdate>
        <message>Would your house be available at this time?</message>
    </enquiry>
    <enquiry>
        <name>Sam Hall</name>
        <email>sam.hall33@gmail.com</email>
        <listingid>3</listingid>
        <bookingdate>27/11/2016 - 3/12/2016</bookingdate>
        <message>Is the area of the bedroom loud at night?</message>
    </enquiry>
</enquiries>
